repos:
  - repo: local # 本地仓库
    hooks:
      - id: check-aws-arn
        name: Hard-coded arn check
        entry: python terry_modules/check_aws_arn.py # 指定脚本入口
        language: python
        files: ^modules/.*\.py$ # 仅检查modules目录下的.py文件
        pass_filenames: true # 向脚本传递文件名参数

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
